### ISSUE TITLE
Messages mentioning you move text to the left

### ISSUE THREAD

**Issue by sawe871** [PseudoResonance/BetterDiscord-Theme#1] opened 2020-02-27 19:12 UTC
When viewing a message that mentions you with `@everyone` or `@name`, the message is moved to the left, either hiding it or obscuring it.

![example 1](https://cdn.discordapp.com/attachments/530014734141882382/682664730640252941/2020-02-27_13-04_1.png)
![example 2](https://cdn.discordapp.com/attachments/172488747164631042/682662147884449876/unknown.png)
![example 3](https://cdn.discordapp.com/attachments/610357693546364929/682663151400910855/unknown.png)

**Comment by PseudoResonance** [comment] 2020-02-28 05:52
I can't reproduce this issue. Are you sure you are using the latest version of the theme? Version 1.1.5?

**Comment by sawe871** [comment] 2020-02-28 20:39
I am using 1.1.5.  I also tried to reproduce it again, and can no longer do so.  Strange.

**Comment by StateOfException** [comment] 2020-02-29 12:56
I've been getting the same issue with 1.1.5 - not sure what seems to have caused it, specifically.  😕
It recurs across application restarts, window size changes, etc.

**Comment by grian32** [comment] 2020-02-29 13:14
Same issue with 1.1.5 , seems to happen since ive gotten the alert on discord for the bandagedbd update, it did mention that they cleaned up some code so maybe theres a issue with that?

just updated the theme and restarted discord.

**Comment by SileNce5k** [comment] 2020-03-01 17:35
Yeah I have the same issue with 1.1.5.

**Comment by EmeraldSnorlax** [comment] 2020-03-01 18:28
Having the same issue ^^

**Comment by AdamEternal** [comment] 2020-03-02 00:31
I am also having the issue, also using 1.1.5.

**Comment by MaxAkito** [comment] 2020-03-02 03:07
Can confirm it still happening.

**Comment by PseudoResonance** [comment] 2020-03-02 09:25
This should be fixed in 1.1.7. I've also added an auto updating loader thing too here: https://github.com/PseudoResonance/BetterDiscord-Theme/blob/master/OldMessagesLoader.theme.css

**Closed** 2020-03-02 09:26 UTC

**Comment by PseudoResonance** [comment] 2020-03-02 09:28
Discord added a new div between the message itself and the message container, and messed with the spacing a lot, making a giant padding, and an equivalent, negative margin...
